source :rubygems

gem "eventmachine"
gem "em-http-request"
gem "nats"
gem "ruby-hmac"
gem "uuidtools"
gem "datamapper", "= 1.1.0"
gem "dm-sqlite-adapter"
gem "do_sqlite3"
gem "sinatra"
gem "thin"

gem "rkerberos"
gem "webhdfs-client", "=0.6.0"
gem "timfel-krb5-auth"
gem "httpi"
gem "httpclient"
gem "curb"

gem 'vcap_common', '~> 1.0.8', :require => ['vcap/common', 'vcap/component']
gem 'vcap_logging', '>=0.1.3', :require => ['vcap/logging']
gem "vcap_services_base"

group :test do
  gem "rake"
  gem "rspec"
  gem "ci_reporter"
end
